services:
  - type: web
    name: sentiment-analysis-webapp
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir webapp app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
